### ISSUE TITLE
Proguard Warnings

### ISSUE THREAD

**Issue by Nolanus** [yongjhih/RxBolts#3]
When creating a release apk of an app that uses RxBolts, the following proguard warnings appear:

```
Warning: rx.bolts.TaskObservable: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning: rx.bolts.TaskObservable: can't find referenced class java.lang.invoke.MethodHandles
Warning: rx.bolts.TaskObservable$$Lambda$1: can't find referenced class java.lang.invoke.LambdaForm$Hidden
Warning: rx.bolts.TaskObservable$$Lambda$2: can't find referenced class java.lang.invoke.LambdaForm$Hidden
Warning: rx.bolts.TaskObservable$$Lambda$3: can't find referenced class java.lang.invoke.LambdaForm$Hidden
Warning: rx.bolts.TaskObservable$$Lambda$4: can't find referenced class java.lang.invoke.LambdaForm$Hidden
Warning: rx.bolts.TaskObservable$$Lambda$5: can't find referenced class java.lang.invoke.LambdaForm$Hidden
Warning: rx.bolts.TaskObservable$$Lambda$6: can't find referenced class java.lang.invoke.LambdaForm$Hidden
```

**Comment by vxhviet** [comment]
Hi @yongjhih,

I'm very much facing this same issue when trying to use ProGuard on the latest `rxParse`:

```
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.2.0'
    compile 'com.infstory:rxparse:2.0.2'
```

The build throws this warning:

```
Warning:rx.bolts.TaskObservable: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning:rx.bolts.TaskObservable: can't find referenced class java.lang.invoke.MethodHandles
```

I'm currently using [these ProGuard rules](https://github.com/artem-zinnatullin/RxJavaProGuardRules/blob/master/rxjava-proguard-rules/proguard-rules.txt) for RxJava:

```
-dontwarn sun.misc.**

-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
   long producerIndex;
   long consumerIndex;
}

-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}

-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}
```

I'm not sure why your ProGuard config doesn't work but a quick search shows this [StackOverflow question](http://stackoverflow.com/questions/26983248/proguard-ignores-config-file-of-library), maybe this is the problem?

**Comment by yongjhih** [comment]
Sorry,  I mistook adding proguard file:
https://github.com/yongjhih/RxBolts/commit/7baa6dbfde7951434b6edacfd655e02f3a30b237

**Comment by vxhviet** [comment]
I can confirm this is the correct rule. I did add this into the main proguard file shortly after asking this question and it works perfectly.  If you add this into the library, I can just use this instead.

Thanks a gain for your prompt reply.

**Comment by vxhviet** [comment]
Sorry @yongjhih, I think you need to update `RxParse` to reference this commit as I don't use `RxBolts` directly and with version 2.0.2 of `RxParse`, this error still show up.

**Comment by yongjhih** [comment]
#2

**Comment by yongjhih** [comment]
@vxhviet, I've updated `RxParse` to 2.0.3 you can try.
