### ISSUE TITLE
onCompleted should be called even with error

### ISSUE THREAD

**Issue by danielsanfr** [yongjhih/RxBolts#4]
I believe the onCompleted method should be called even if the call has an error.
This is my example:

``` java
showLoading()
ParseObservable.logIn(email, password)
        .doOnCompleted(() -> dismissLoading())
        .doOnNext(parseUser -> Log.d("=========", "onClickLogin: " + parseUser))
        .doOnError(throwable -> Log.e("*********", "onClickLogin: ", throwable))
        .subscribe();
```

The code for this is in: https://github.com/yongjhih/RxBolts/blob/master/rxbolts-tasks/src/main/java/rx/bolts/TaskObservable.java#L52

**Comment by PavelSynek** [comment]
> An Observable may make zero or more OnNext notifications, each representing a single emitted item, and it may then follow those emission notifications by **either an OnCompleted or an OnError notification, but not both**.

http://reactivex.io/documentation/contract.html

**Comment by danielsanfr** [comment]
Sorry that I did not read that part of the Rx documentation.
After reading this, I ended up finding the solution:

``` java
showLoading()
ParseObservable.logIn(email, password)
        .doOnNext(parseUser -> Log.d("=========", "onClickLogin: " + parseUser))
        .doOnError(throwable -> Log.e("*********", "onClickLogin: ", throwable))
        .doOnTerminate(() -> dismissLoading())
        .subscribe();
```

Thanks a lot for the help!
